snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://bodas@localhost/1'
        cache:
            type: predis
            alias: cache
            dsn: 'redis://bodas@localhost/1'
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
