parameters:

imports:
    - { resource: services/commandbus.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DevBodas\Shared\Infrastructure\:
        resource: '../src/Shared/Infrastructure/*'

    DevBodas\Dev\Application\:
        resource: '../src/Dev/Application'
        exclude: '../src/Dev/Application/{Command}'

    DevBodas\Dev\Infrastructure\EntryPoint\Controller\:
        resource: '../src/Dev/Infrastructure/EntryPoint/Controller'
        tags: [ 'controller.service_arguments' ]

    DevBodas\Dev\Domain\Repository\SimulatorRepository:
        class: 'DevBodas\Dev\Infrastructure\Repository\Persistence\MysqlSimulatorRepository'
        arguments: [ '@doctrine.orm.entity_manager' ]

